### ISSUE TITLE
Allow override of AC installation directory

### ISSUE THREAD

**Issue by predominant** [eric-johnson-space-administration/EJSA-AC-Mod-Manager#3]
If user has a separate installation or multiple installations, auto-detection will pickup the first found install.
Allow advanced users to override the path to their specified directory, and persist that setting to user preferences for the app.
Also allow user to "auto-discover" later, if they want to revert to automatic behaviour

**Comment by MrDrummer** [comment]
I'm curious - is there a benefit to having the software _installed_? Other than of course having a star menu shortcut.

Also I'm guessing it'll have to have a portable option to allow for multiple installs like you mention?

**Comment by predominant** [comment]
The "installs" mentioned in this ticket refer to Assetto Corsa installs.

**Comment by predominant** [comment]
Done
